### ISSUE TITLE
What's holding off putting out a first release of this?

### ISSUE THREAD

**Issue by blakebyrnes** [libp2p/js-libp2p-nat-mngr#3]
Looks like a lot of good progress in the wip branch.  Anything stopping this from getting merged into master?

**Comment by jacobheun** [comment]
https://github.com/libp2p/js-libp2p-nat-mngr/issues/2 is the blocker, just permissions. Working on getting that resolved so I can get the WIP into master so we can make progress from there.

**Comment by jacobheun** [comment]
I've got that merged so we can start iterating more easily. The initial release is on my list for this quarter.  Closing this.
